name: Deploy Repi LINE webhook to Cloud Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Deploy Cloud Functions v2 (repi-webhook)
        run: |
          gcloud functions deploy repiWebhook \
            --gen2 \
            --region="${{ vars.GCP_REGION }}" \
            --runtime=nodejs20 \
            --source=cloud/functions/repi-webhook \
            --entry-point=repiWebhook \
            --trigger-http --allow-unauthenticated \
            --set-env-vars FIREBASE_PROJECT_ID=${{ vars.FIREBASE_PROJECT_ID }},OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }},LINE_CHANNEL_SECRET_REPI=${{ secrets.LINE_CHANNEL_SECRET_REPI }},LINE_CHANNEL_ACCESS_TOKEN_REPI=${{ secrets.LINE_CHANNEL_ACCESS_TOKEN_REPI }}
